"""changed seasons property to string

Revision ID: 1f37d0013285
Revises: 2833e470427f
Create Date: 2025-01-31 06:35:52.762064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f37d0013285'
down_revision = '2833e470427f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bikeshares', schema=None) as batch_op:
        batch_op.alter_column('seasons',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bikeshares', schema=None) as batch_op:
        batch_op.alter_column('seasons',
               existing_type=sa.String(length=40),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
