"""initial migration

Revision ID: 70971ffd486e
Revises: 
Create Date: 2025-01-31 06:02:05.215865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70971ffd486e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bikeshares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('windspeed', sa.Float(), nullable=False),
    sa.Column('visibility', sa.Integer(), nullable=False),
    sa.Column('dewpointtemperature', sa.Float(), nullable=False),
    sa.Column('solarradiation', sa.Float(), nullable=False),
    sa.Column('rainfall', sa.Float(), nullable=False),
    sa.Column('snowfall', sa.Float(), nullable=False),
    sa.Column('seasons', sa.Float(), nullable=False),
    sa.Column('holiday', sa.String(length=20), nullable=False),
    sa.Column('functioningday', sa.String(length=4), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('dayofweek', sa.Integer(), nullable=False),
    sa.Column('hoursin', sa.Float(), nullable=False),
    sa.Column('hourcos', sa.Float(), nullable=False),
    sa.Column('bikecount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bikeshares')
    # ### end Alembic commands ###
