"""changed bikecount from int to float

Revision ID: 899c1dc1b992
Revises: 1f37d0013285
Create Date: 2025-01-31 06:37:16.670796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899c1dc1b992'
down_revision = '1f37d0013285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bikeshares', schema=None) as batch_op:
        batch_op.alter_column('bikecount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bikeshares', schema=None) as batch_op:
        batch_op.alter_column('bikecount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
