services:
  # app:
  #   build: 
  #     context: ./app
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - FLASK_APP="app.py"
  #     - FLASK_ENV="development"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  
  db:
    image: "postgres:15"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=bikeshare
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db_data: