version: '3.8'

services:
  app:
    build: .
    ports:
      - "9696:9696"
    depends_on:
      - db
    environment:
      DATABASE_URI: "postgresql+psycopg2://user:password@db:5432/bike_sharing"
    command: ["python", "app.py"]

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bike_sharing
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: